import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'superbowl-squares';

  names = [
    'Alan Krajbich',
    'Marina Kiperberg',
    'Eva Guest',
    'Ashley Lamplough',
   ' Erez Guest',
    'Kelley Maniatakos',
    'Gloria Cheung',
    'Chris – Guest',
    'Mary Sylvia',
    'Ross Caisse',
    'Diana Arita',
    'Gloria Cheung',
    'Kelley - Guest 1',
    'Bobby Donald',
    'Eva Guest',
    'Chris – Guest',
    'Eva Bitteker',
    'Erez Guest',
    'Gloria Cheung',
    'Wayne Luan',
    'Diana Arita',
    'Chris – Guest',
    'Chris Farley',
    'Alan Krajbich',
    'Ross Caisse',
    'Erez Almog',
    'Mary Sylvia',
    'Ashley Lamplough',
    'Raj Naik',
    'Erez Almog',
    'Diana Arita',
    'Andrew Karlson',
    'Kelley - Guest 2',
    'Mary Sylvia',
    'Wayne Luan',
    'Marina Kiperberg',
    'Eva Guest',
    'Diana Arita',
    'Gloria Cheung',
    'Mary Sylvia',
    'Chris – Guest',
    'Chris Farley',
    'Kelley - Guest 1',
    'Bobby Donald',
    'Ashley Lamplough',
    'Kelley - Guest 1',
    'Raj Naik',
    'Erez Guest',
    'Kelley - Guest 2',
    'Erez Guest',
    'Chris Farley',
    'Kelley Maniatakos',
    'Diana Arita',
    'Wayne Luan',
    'Alan Krajbich',
    'Bobby Donald',
    'Kelley - Guest 1',
    'Ashley Lamplough',
    'Mary Sylvia',
    'Eva Bitteker',
    'Ross Caisse',
    'Erez Guest',
    'Chris Farley',
    'Chris – Guest',
    'Chris Farley',
    'Erez Almog',
    'Gloria Cheung',
    'Eva Bitteker',
    'Kelley - Guest 2',
    'Kelley - Guest 2',
    'Andrew Karlson',
    'Andrew Karlson',
    'Kelley Maniatakos',
    'Marina Kiperberg',
    'Kelley Maniatakos',
    'Raj Naik',
    'Marina Kiperberg',
    'Raj Naik',
    'Kelley - Guest 2',
    'Bobby Donald',
    'Eva Bitteker',
    'Bobby Donald',
    'Andrew Karlson',
    'Marina Kiperberg',
    'Eva Guest',
    'Wayne Luan',
    'Raj Naik',
    'Ross Caisse',
    'Wayne Luan',
    'Eva Guest',
    'Ashley Lamplough',
    'Alan Krajbich',
    'Eva Bitteker',
    'Andrew Karlson',
    'Kelley Maniatakos',
    'Ross Caisse',
    'Erez Almog',
    'Kelley - Guest 1',
    'Alan Krajbich',
    'Erez Almog',
  ]
}
